services:

  ui:
    image: shumilomaks/fakely-live-ui:1.1.1
    ports:
      - "443:443"
      - "80:80"
    container_name: fakely_live_ui
    restart: unless-stopped
    depends_on:
      - api

  api:
    network_mode: host
    restart: always
    container_name: fakely_live_api
    image: shumilomaks/fakely-live-api:1.0.3
    volumes:
      - ./faces/:/usr/src/app/src/faces/
    env_file: .env
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy

  frames-handler:
    container_name: fakely_live_frames_handler
    image: shumilomaks/fakely-live-frames-handler:1.0.1
    volumes:
      - ./models/:/usr/src/app/models/
    env_file: .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy

  rabbitmq:
    restart: always
    image: rabbitmq:3.12-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: [ "CMD-SHELL", "rabbitmq-diagnostics check_running || exit 1" ]
      interval: 15s
      timeout: 10s
      retries: 3


  redis:
    image: redis:7.0-alpine
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping" ]
      interval: 15s
      timeout: 10s
      retries: 3
