services:

  api:
    restart: always
    image: deepfake-live/api:latest
    build:
      context: .
    ports:
      - "9696:9696"
    environment:
      - RABBITMQ_HOST=10.8.0.1
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - ENABLE_HANDLE_STREAM=1

  rabbitmq:
    restart: always
    image: rabbitmq:3.12-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
