name: Build and Publish UI Image

on:
  push:
    branches: [ main ]
    paths:
      - 'ui/**'
      - '.github/workflows/ui-build.yml'

jobs:
  build:
    name: Build UI Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: shumilomaks/fakely-live-ui
          tags: |
            type=sha,format=short
            latest
            1.0.0
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./ui
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=shumilomaks/fakely-live-ui:buildcache
          cache-to: type=registry,ref=shumilomaks/fakely-live-ui:buildcache,mode=max